[package]
name = "actix-redis"
version = "0.8.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Redis integration for actix framework"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["web", "redis", "async", "actix", "tokio"]
homepage = "https://github.com/actix/actix-redis"
repository = "https://github.com/actix/actix-redis.git"
documentation = "https://docs.rs/actix-redis/"
categories = ["network-programming", "asynchronous"]
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[lib]
name = "actix_redis"
path = "src/lib.rs"

[badges]
travis-ci = { repository = "actix/actix-redis", branch = "master" }
codecov = { repository = "actix/actix-redis", branch = "master", service = "github" }

[features]
default = ["web"]

# actix-web integration
web = ["actix/http", "actix-service", "actix-web", "actix-session/cookie-session", "rand", "serde", "serde_json"]

[dependencies]
actix = "0.9.0"
actix-utils = "1.0.3"

log = "0.4.6"
backoff = "0.1.5"
derive_more = "0.99.2"
futures = "0.3.1"
redis-async = "0.6.1"
actix-rt = "1.0.0"
time = { version = "0.2.5", default-features = false, features = ["std"] }
tokio = "0.2.6"
tokio-util = "0.2.0"

# actix web session
actix-web = { version = "2.0.0", optional = true }
actix-service = { version = "1.0.0", optional = true }
actix-session = { version = "0.3.0", optional = true }
rand = { version = "0.7.0", optional = true }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
serde_json = { version = "1.0.40", optional = true }
env_logger = "0.6.2"

[dev-dependencies]
env_logger = "0.6"
