[package]
name = "actix-redis"
version = "0.4.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Redis integration for actix framework"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["web", "redis", "async", "actix", "tokio"]
homepage = "https://github.com/actix/actix-redis"
repository = "https://github.com/actix/actix-redis.git"
documentation = "https://docs.rs/actix-redis/"
categories = ["network-programming", "asynchronous"]
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]

[lib]
name = "actix_redis"
path = "src/lib.rs"

[badges]
travis-ci = { repository = "actix/actix-redis", branch = "master" }
codecov = { repository = "actix/actix-redis", branch = "master", service = "github" }

[features]
default = ["web"]

# actix-web integration
web = ["actix-web", "cookie", "http", "rand", "serde", "serde_json"]

[dependencies]
actix = "0.5"

log = "0.4"
backoff = "0.1"
failure = "^0.1.1"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
redis-async = ">= 0.0.6,  < 0.4"

# actix web session
actix-web = { version="0.6", optional=true }
cookie = { version="0.10", features=["percent-encode", "secure"], optional=true }
http = { version="0.1", optional=true }
rand = { version="0.5", optional=true }
serde = { version="1.0", optional=true }
serde_json = { version="1.0", optional=true }

[dev-dependencies]
env_logger = "0.5"
